/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_teoriabd_1;
import java.awt.Color;
import java.sql.Statement;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;

//pdfimports
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileOutputStream;
/**
 *
 * @author Tyler C
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public main() {
        initComponents();
        //this.JB_Start_main.setBackground(Color.red);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main_JPanel = new javax.swing.JPanel();
        JB_Start_main = new javax.swing.JButton();
        JL_ShipperName_main = new javax.swing.JLabel();
        JL_CustomerName_main = new javax.swing.JLabel();
        JL_ShipName_main = new javax.swing.JLabel();
        JL_Employee_Name_main = new javax.swing.JLabel();
        JL_Weight_main = new javax.swing.JLabel();
        JL_ShipAddress_main = new javax.swing.JLabel();
        JL_ShipRegion_main = new javax.swing.JLabel();
        JL_ShipCity_main = new javax.swing.JLabel();
        JL_ShipPostalCode_main = new javax.swing.JLabel();
        JL_Country_main = new javax.swing.JLabel();
        JL_Country_main1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        background_main = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        main_JPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JB_Start_main.setBackground(new java.awt.Color(255, 255, 153));
        JB_Start_main.setText("Start");
        JB_Start_main.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_Start_mainActionPerformed(evt);
            }
        });
        main_JPanel.add(JB_Start_main, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        JL_ShipperName_main.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JL_ShipperName_main.setForeground(new java.awt.Color(255, 255, 255));
        JL_ShipperName_main.setText("Shipper Name:");
        main_JPanel.add(JL_ShipperName_main, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        JL_CustomerName_main.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JL_CustomerName_main.setForeground(new java.awt.Color(255, 255, 255));
        JL_CustomerName_main.setText("Customer Name:");
        main_JPanel.add(JL_CustomerName_main, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        JL_ShipName_main.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JL_ShipName_main.setForeground(new java.awt.Color(255, 255, 255));
        JL_ShipName_main.setText("ShipName:");
        main_JPanel.add(JL_ShipName_main, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        JL_Employee_Name_main.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JL_Employee_Name_main.setForeground(new java.awt.Color(255, 255, 255));
        JL_Employee_Name_main.setText("Employee Name:");
        main_JPanel.add(JL_Employee_Name_main, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        JL_Weight_main.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JL_Weight_main.setForeground(new java.awt.Color(255, 255, 255));
        JL_Weight_main.setText("Weight:");
        main_JPanel.add(JL_Weight_main, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        JL_ShipAddress_main.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JL_ShipAddress_main.setForeground(new java.awt.Color(255, 255, 255));
        JL_ShipAddress_main.setText("Ship Address:");
        main_JPanel.add(JL_ShipAddress_main, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        JL_ShipRegion_main.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JL_ShipRegion_main.setForeground(new java.awt.Color(255, 255, 255));
        JL_ShipRegion_main.setText("Ship Region:");
        main_JPanel.add(JL_ShipRegion_main, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, -1, -1));

        JL_ShipCity_main.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JL_ShipCity_main.setForeground(new java.awt.Color(255, 255, 255));
        JL_ShipCity_main.setText("Ship City:");
        main_JPanel.add(JL_ShipCity_main, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, -1, -1));

        JL_ShipPostalCode_main.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JL_ShipPostalCode_main.setForeground(new java.awt.Color(255, 255, 255));
        JL_ShipPostalCode_main.setText("Ship Postal Code:");
        main_JPanel.add(JL_ShipPostalCode_main, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, -1, -1));

        JL_Country_main.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JL_Country_main.setForeground(new java.awt.Color(255, 255, 255));
        JL_Country_main.setText("Country:");
        main_JPanel.add(JL_Country_main, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, -1, -1));

        JL_Country_main1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        JL_Country_main1.setForeground(new java.awt.Color(255, 255, 255));
        JL_Country_main1.setText("Generate New Order");
        main_JPanel.add(JL_Country_main1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select.." }));
        main_JPanel.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 140, -1));

        background_main.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delivery_background.jpg"))); // NOI18N
        main_JPanel.add(background_main, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 340));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main_JPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main_JPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JB_Start_mainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_Start_mainActionPerformed
        // TODO add your handling code here:
        MariaDB conn = new MariaDB();
        Statement stm = null;
        conn.connectNorthwind();
        conn.pdfCreator();
//        conn.test();
//        Connection con = conn.getDbcon();
//        try {
//            stm = con.createStatement();
//            stm.executeQuery("Select * from customers");
//            ResultSet rs = stm.executeQuery("Select * from customers");
//            while (rs.next()) {
//            }
//             System.out.println("registry: " + rs.getString(1));
//        } catch (SQLException ex) {
//            Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
//        }
        conn.disconnectNorthwind();
        
    }//GEN-LAST:event_JB_Start_mainActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB_Start_main;
    private javax.swing.JLabel JL_Country_main;
    private javax.swing.JLabel JL_Country_main1;
    private javax.swing.JLabel JL_CustomerName_main;
    private javax.swing.JLabel JL_Employee_Name_main;
    private javax.swing.JLabel JL_ShipAddress_main;
    private javax.swing.JLabel JL_ShipCity_main;
    private javax.swing.JLabel JL_ShipName_main;
    private javax.swing.JLabel JL_ShipPostalCode_main;
    private javax.swing.JLabel JL_ShipRegion_main;
    private javax.swing.JLabel JL_ShipperName_main;
    private javax.swing.JLabel JL_Weight_main;
    private javax.swing.JLabel background_main;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JPanel main_JPanel;
    // End of variables declaration//GEN-END:variables
}
